### ISSUE TITLE
Can not unmarshal JSON invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by avephill** [StefanAbl/jellyfin-prometheus-exporter#3]
This was working, but I think I updated jellyfin to 10.8.11 and it no longer works. I'm running it as a docker container and when I run `docker-compose logs -f jellyfin-exporter` I get `Can not unmarshal JSON invalid character '<' looking for beginning of value` repeatedly.

**Comment by StefanAbl** [comment]
Hey, thank you for testing my code with the newest release. 

Unfortunately,  I was not able to replicate your error with the demo instance.  
However,  I did encounter this error when the path to the jellyfin instance was not set correctly.

I will try to update my personal jellyfin server soon, and then I can give you a definitive answer.

**Comment by avephill** [comment]
Great, thank you very much. I'll try making sure the path is set correctly later today. If it's working for you I can mess around with my config a bit more and try to isolate it myself. Thanks!

**Comment by StefanAbl** [comment]
After updating my personal instance to 10.8.11 the exporter still works as expected. I set the JF_URL to `https://jellyfin.${DOMAIN}:8920/`. Note that it ends with a `/`

**Comment by avephill** [comment]
Ah, thanks so much for getting back to me. I had actually monkeyed around with the `base url` in jellyfin network config and after setting my url to `http://[server_url]:8920/jellyfin` everything worked. Thanks for helping me.
